apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./v-rising.yaml
  # - ./v-rising-config.yaml

# configMapGenerator:
# - name: vrising-ServerHostSettings
#   files:
#   - ServerHostSettings.json
# - name: vrising-ServerGameSettings
#   files:
#   - ServerGameSettings.json